[project]
name = "tessl-hackathon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.11.7",
    "pydantic-ai[logfire]>=0.6.0",
    "logfire>=4.2.0",
    "turbopuffer>=0.6.0",
]
